### ISSUE TITLE
Data preprocess

### ISSUE THREAD

**Issue by YibinLiu666** [HKUDS/RLMRec#14]
Hello, I am very interested in your work and would like to process and reproduce your code from the raw data, so that I can do further research. I see that you mentioned in your paper that the data with a score of less than 3 in the Amazon-book and yelp datasets is filtered, and k-core is also filtered on Steam, can you provide the code about this part of preprocessing?

**Comment by Re-bin** [comment]
Hi 👋!

Thanks for your interests on RLMRec! Due to the complexity of the pre-processing code and its multi-file structure, it might be more helpful to provide a straightforward overview of the basic workflow for the pre-processing steps, as outlined below:

1. **Score Filtering**: Begin by filtering out low-score interactions (implemented using a for loop).
2. **User Sampling** (Discussion in [Issue 9](https://github.com/HKUDS/RLMRec/issues/9)) Next, uniformly sample a ratio of users and remove items that have not been interacted with after filtering the users. This will help reduce the dataset size (implemented with boolean vectors).
3. **K-Core Filtering**: Finally, apply k-core filtering using the `NetworkX` library.

I hope the above answer is helpful to you :)

Best regards,
Xubin

**Comment by YibinLiu666** [comment]
> Hi 👋!
> 
> Thanks for your interests on RLMRec! Due to the complexity of the pre-processing code and its multi-file structure, it might be more helpful to provide a straightforward overview of the basic workflow for the pre-processing steps, as outlined below:
> 
> 1. **Score Filtering**: Begin by filtering out low-score interactions (implemented using a for loop).
> 2. **User Sampling** (Discussion in [Issue 9](https://github.com/HKUDS/RLMRec/issues/9)) Next, uniformly sample a ratio of users and remove items that have not been interacted with after filtering the users. This will help reduce the dataset size (implemented with boolean vectors).
> 3. **K-Core Filtering**: Finally, apply k-core filtering using the `NetworkX` library.
> 
> I hope the above answer is helpful to you :)
> 
> Best regards, Xubin

Thank you for your reply!
